apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3proxy-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: "/Users/rcurrie/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3proxy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3proxy
  template:
    metadata:
      labels:
        app: s3proxy
    spec:
      containers:
        - name: s3proxy
          image: andrewgaul/s3proxy
          env:
            - name: S3PROXY_IDENTITY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: access-key-id
            - name: S3PROXY_CREDENTIAL
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret-access-key
            - name: JCLOUDS_PROVIDER
              value: "filesystem"
            - name: JCLOUDS_FILESYSTEM_BASEDIR
              value: "/data"
            - name: S3PROXY_ENDPOINT
              value: "http://0.0.0.0:9000"
            - name: S3PROXY_AUTHORIZATION
              value: "aws-v2-or-v4"
          ports:
            - containerPort: 9000
              name: api
          volumeMounts:
            - mountPath: /data
              name: s3proxy-storage
      volumes:
        - name: s3proxy-storage
          persistentVolumeClaim:
            claimName: s3proxy-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: s3proxy-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000
      name: api
  selector:
    app: s3proxy
