# [build-system]
# requires = ["hatchling", "setuptools>=61.0", "wheel0"]
# build-backend = "setuptools.build_meta"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cytoverse"
version = "0.1.0"
requires-python = ">=3.12, <3.13"
dependencies = [
    "typer>=0.16.0",
    "anndata>=0.12.1",
    "scimilarity",
    "umap-pytorch",
    "pyarrow>=21.0.0",
    "scanpy>=1.11.4",
    "numpy>=1.24,<2.3",
    "scipy>=1.16.1",
    "scikit-learn>=1.7.1",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "onnx>=1.18.0",
    "onnxruntime>=1.22.1",
    "onnxscript>=0.3.2",
    "s3fs>=2024.1.0",
    "boto3>=1.35.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "debugpy>=1.8.15",
    "flake8>=7.2.0",
    "graphviz>=0.21",
    "ipython>=8.37.0",
    "jupyter>=1.1.1",
    "jupyter-console>=6.6.3",
    "mypy>=1.19.1",
    "netron>=8.3.9",
    "pandas-stubs>=2.3.3.251219",
    "pytest>=8.0.0",
    "ruff>=0.14.10",
    "types-tqdm>=4.67.0.20250809",
]
[[tool.mypy.overrides]]
module = ["scanpy", "scimilarity.*", "onnxruntime.*"]
follow_untyped_imports = true
ignore_missing_imports = true

[tool.uv.sources]
scimilarity = { git = "https://github.com/Genentech/scimilarity.git" }
umap-pytorch = { git = "https://github.com/rcurrie/umap_pytorch.git" }

[tool.uv]
override-dependencies = ["umap-learn>=0.5.0", "numba>=0.60.0"]

[tool.hatch.build.targets.wheel]
packages = ["backend/src"]

[tool.pytest.ini_options]
pythonpath = ["backend/src"]
testpaths = ["backend/tests"]
filterwarnings = [
    "ignore::DeprecationWarning:anndata._settings",
    "ignore:You are using the legacy TorchScript-based ONNX export:DeprecationWarning",
    "ignore:The feature will be removed. Please remove usage of this function:DeprecationWarning:torch.onnx.utils",
    "ignore:divide by zero encountered in matmul:RuntimeWarning:sklearn.utils.extmath",
    "ignore:overflow encountered in matmul:RuntimeWarning:sklearn.utils.extmath",
    "ignore:invalid value encountered in matmul:RuntimeWarning:sklearn.utils.extmath",
    "ignore:divide by zero encountered in matmul:RuntimeWarning:sklearn.cluster._kmeans",
    "ignore:overflow encountered in matmul:RuntimeWarning:sklearn.cluster._kmeans",
    "ignore:invalid value encountered in matmul:RuntimeWarning:sklearn.cluster._kmeans",
    "ignore:Number of distinct clusters.*found smaller than n_clusters:sklearn.exceptions.ConvergenceWarning",
    "ignore:torch.tensor results are registered as constants in the trace:torch.jit.TracerWarning",
    "ignore:Avoid using this function and create a Cast node instead:DeprecationWarning:torch.onnx.symbolic_opset9",
]
