[project]
name = "cellspace"
version = "0.1.0"
description = "Search, display and label cells in foundation model embedding space"
readme = "README.md"
requires-python = ">=3.10, <3.12"
dependencies = [
    "typer>=0.16.0",
    "onnx>=1.18.0",
    "onnxruntime>=1.15.0",
    "scimilarity",
    # "scimilarity==0.4.0.post1.dev3+g52824e5"
    "umap-pytorch",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
    "torchaudio>=2.7.1",
    "anndata>=0.11.4",
    "zarr<3.0",
    "pytorch-lightning>=2.5.2",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "flake8>=7.2.0",
    "ipython>=8.37.0",
    "jupyter>=1.1.1",
    "jupyter-console>=6.6.3",
    "netron>=8.3.9",
]

[tool.uv.sources]
scimilarity = { path = "../scimilarity" }
umap-pytorch = { path = "../umap_pytorch", editable = true }
