[project]
name = "cytoverse"
version = "0.1.0"
description = "Search, display and label cells in foundation model embedding space"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "typer>=0.16.0",
    "onnx>=1.18.0",
    "onnxruntime>=1.15.0",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
    "anndata>=0.12.1",
    "pytorch-lightning>=2.5.2",
    "scimilarity",
    "umap-pytorch",
    "ray[data,train,tune]>=2.48.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "flake8>=7.2.0",
    "ipython>=8.37.0",
    "jupyter>=1.1.1",
    "jupyter-console>=6.6.3",
    "netron>=8.3.9",
    "pytest>=8.0.0",
]

[tool.uv.sources]
scimilarity = { git = "https://github.com/Genentech/scimilarity.git" }
umap-pytorch = { git = "https://github.com/rcurrie/umap_pytorch.git" }
