"""Generate the LaTeX overlay for Figure 1 from the measured callout anchors.

The numbered markers are drawn by TikZ over the screenshot rather than baked
into the image. That keeps them as live vector text at full quality regardless
of the raster underneath, lets the legend live in the caption in body font (the
Phase 0 decision), and sidesteps the CropBox/MediaBox hazard that came with the
old Google Slides export.

Reads  paper/figures/captured/fig1_ui_guide.callouts.json  (written by the
Playwright capture) and writes  paper/figures/fig1_ui_guide.tex.

    uv run scripts/figures/fig1_callouts_tex.py
"""

from __future__ import annotations

import json
from pathlib import Path

ANCHORS = Path("paper/figures/captured/fig1_ui_guide.callouts.json")
OUT = Path("paper/figures/fig1_ui_guide.tex")
WIDTH_MM = 174

PREAMBLE_NOTE = r"""% Generated by scripts/figures/fig1_callouts_tex.py -- do not edit by hand.
%
% Requires in the preamble:   \usepackage{tikz}
%
% The screenshot is placed at its natural print width (174 mm). Callout
% coordinates are fractions of the image, so the markers track the artwork if it
% is ever resized or recaptured.
"""


def main() -> None:
    data = json.loads(ANCHORS.read_text())
    anchors = data["anchors"]

    lines: list[str] = [PREAMBLE_NOTE]
    lines.append(r"\begin{figure}[htbp]")
    lines.append(r"  \centering")
    lines.append(r"  \begin{tikzpicture}[")
    lines.append(r"    callout/.style={circle, fill=white, draw=black!55,")
    lines.append(r"                    line width=0.3pt, text=black, inner sep=0pt,")
    lines.append(r"                    minimum size=3.6mm,")
    lines.append(r"                    font=\sffamily\bfseries\scriptsize}]")
    lines.append(
        rf"    \node[anchor=south west, inner sep=0] (fig1) at (0,0)"
        rf"%\n      {{\includegraphics[width={WIDTH_MM}mm]{{fig1_ui_guide.png}}}};"
    )
    lines.append(r"    \begin{scope}[x={(fig1.south east)}, y={(fig1.north west)}]")
    for a in anchors:
        # JSON y is measured from the top (DOM convention); TikZ y runs upward.
        lines.append(
            f"      \\node[callout] at ({a['x']:.4f},{1 - a['y']:.4f}) {{{a['n']}}};"
        )
    lines.append(r"    \end{scope}")
    lines.append(r"  \end{tikzpicture}")

    legend = [a for a in anchors if a["legend"]]
    caption = [r"  \caption{CytoVerse user interface. Numbered markers:"]
    for i, a in enumerate(legend):
        end = "." if i == len(legend) - 1 else ";"
        caption.append(f"    \\textbf{{{a['n']}}}~{a['legend']}{end}")
    caption.append("  }")
    lines.extend(caption)
    lines.append(r"  \label{fig:ui_guide}")
    lines.append(r"\end{figure}")

    OUT.write_text("\n".join(lines).replace("%\\n", "\n") + "\n")
    print(f"  wrote {OUT}  ({len(anchors)} markers, {len(legend)} legend entries)")


if __name__ == "__main__":
    main()
